<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KIS4N2E" failures="1" tests="4" name="listenerStudy.MyClass" time="0.020" errors="0" timestamp="2024-08-01T08:03:45 IST" skipped="1">
  <testcase classname="listenerStudy.MyClass" name="a" time="0.002">
    <system-out>
      <![CDATA[TC a execution started
a is running
TC a completed successfully]]>
    </system-out>
  </testcase> <!-- a -->
  <testcase classname="listenerStudy.MyClass" name="d" time="0.002">
    <system-out>
      <![CDATA[TC d execution started
d is running
TC d completed successfully]]>
    </system-out>
  </testcase> <!-- d -->
  <testcase classname="listenerStudy.MyClass" name="c" time="0.015">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listenerStudy.MyClass.c(MyClass.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[TC c execution started
TC c failed]]>
    </system-out>
  </testcase> <!-- c -->
  <testcase classname="listenerStudy.MyClass" name="b" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[TC b is skipped]]>
    </system-out>
  </testcase> <!-- b -->
  <system-out>
    <![CDATA[TC c execution started
TC c failed
TC d execution started
d is running
TC d completed successfully
TC a execution started
a is running
TC a completed successfully
TC b execution started
TC b is skipped]]>
  </system-out>
</testsuite> <!-- listenerStudy.MyClass -->
